services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - air_quality_net
  
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      POSTGRES_DB: air_quality
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: always
    networks:
      - air_quality_net

volumes:
  timescale-data:

networks:
  air_quality_net: